export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL";

export const GET_PRESENTATIONS_REQUEST = "GET_PRESENTATIONS_REQUEST";
export const GET_PRESENTATIONS_SUCCESS = "GET_PRESENTATIONS_SUCCESS";
export const GET_PRESENTATIONS_FAIL = "GET_PRESENTATIONS_FAIL";

export const GET_PROGRESS_REQUEST = "GET_PROGRESS_REQUEST";
export const GET_PROGRESS_SUCCESS = "GET_PROGRESS_SUCCESS";
export const GET_PROGRESS_FAIL = "GET_PROGRESS_FAIL";

export const ADD_PROGRESS_REQUEST = "ADD_PROGRESS_REQUEST";
export const ADD_PROGRESS_SUCCESS = "ADD_PROGRESS_SUCCESS";
export const ADD_PROGRESS_FAIL = "ADD_PROGRESS_FAIL";
