export const GET_PRESENTATIONS_REQUEST = "GET_PRESENTATIONS_REQUEST";
export const GET_PRESENTATIONS_SUCCESS = "GET_PRESENTATIONS_SUCCESS";
export const GET_PRESENTATIONS_FAIL = "GET_PRESENTATIONS_FAIL";

export const ADD_PRESENTATION_REQUEST = "ADD_PRESENTATION_REQUEST";
export const ADD_PRESENTATION_SUCCESS = "ADD_PRESENTATION_SUCCESS";
export const ADD_PRESENTATION_FAIL = "ADD_PRESENTATION_FAIL";

export const DELETE_PRESENTATION_REQUEST = "DELETE_PRESENTATION_REQUEST";
export const DELETE_PRESENTATION_SUCCESS = "DELETE_PRESENTATION_SUCCESS";
export const DELETE_PRESENTATION_FAIL = "DELETE_PRESENTATION_FAIL";

export const UPDATE_PRESENTATION_REQUEST = "UPDATE_PRESENTATION_REQUEST";
export const UPDATE_PRESENTATION_SUCCESS = "UPDATE_PRESENTATION_SUCCESS";
export const UPDATE_PRESENTATION_FAIL = "UPDATE_PRESENTATION_FAIL";
